export const LOGIN_MODAL_ACTIVATION = 'LOGIN_MODAL_ACTIVATION';
export const REGISTRATION_MODAL_ACTIVATION = 'REGISTRATION_MODAL_ACTIVATION';
export const CREATE_DIRECTORY_MODAL_ACTIVATION = 'CREATE_DIRECTORY_MODAL_ACTIVATION';
export const OPEN_POP_UP = 'OPEN_POP_UP';
