export const LOGIN_MODAL_ACTIVATION = 'LOGIN_MODAL_ACTIVATION';
export const REGISTRATION_MODAL_ACTIVATION = 'REGISTRATION_MODAL_ACTIVATION';
export const CREATE_DIRECTORY_MODAL_ACTIVATION = 'CREATE_DIRECTORY_MODAL_ACTIVATION';
export const OPEN_POP_UP = 'OPEN_POP_UP';
export const PLACES_DETAILS_MODAL_ACTIVATION = 'PLACES_DETAILS_MODAL_ACTIVATION';
export const CHANGE_DATA_ABOUT_USER_MODAL_ACTIVATION = 'CHANGE_DATA_ABOUT_USER_MODAL_ACTIVATION';
export const CHANGE_PASSWORD_MODAL_ACTIVATION = 'CHANGE_PASSWORD_MODAL_ACTIVATION';
export const CLOSE_MODAL = 'CLOSE_MODAL';
