export const GET_DATA_ABOUT_RECIPES_CONFIRMED_ACTIONS = 'GET_DATA_ABOUT_RECIPES_CONFIRMED_ACTIONS';
export const GET_DATA_ABOUT_RECIPES_FAILED_ACTIONS = 'GET_DATA_ABOUT_RECIPES_FAILED_ACTIONS';
export const FAVOURITE_RECIPES = 'FAVOURITE_RECIPES';
