export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_UNAUTHENTICATED = 'USER_UNAUTHENTICATED';
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_UNREGISTERED = 'USER_UNREGISTERED';
export const GET_DATA_ABOUT_USER_SUCCESS = 'GET_DATA_ABOUT_USER_SUCCESS';
export const GET_DATA_ABOUT_USER_FAILED = 'GET_DATA_ABOUT_USER_FAILED';